version: "2"
linters:
  default: all
  disable:
    - depguard  # We have no restrictions on dependencies.
    - err113  # I think it's ok to include info in errors without defining a new type.
    - exhaustruct  # This doesn't make sense to check for in most cases.
    - forbidigo  # nothing to forbid
    - gochecknoglobals  # I don't think globals should be universally disallowed.
    - gochecknoinits  # I don't think init should be universally disallowed.
    - mnd  # prefer goconst
    - nonamedreturns  # disagree
    - tagliatelle  # We have to use the JSON fields from the API.
    - varnamelen  # I don't think this matters.
    - wrapcheck  # I think this should only happen for public functions.
    - wsl  # replaced by wsl_v5
    - wsl_v5  # yuck
  settings:
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: true
    funcorder:
      struct-method: false
    funlen:
      lines: 100
      statements: 50
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - fieldalignment
      enable-all: true
    ireturn:
      allow:
        - error
        - generic
    lll:
      line-length: 100
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kylrth/api
